# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
#namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Openstack Dashboards
#################################################

- name: dashboards-tempest-overview
  files: [ dashboards/tempest-overview.json ]
  options:
    annotations:
      grafana_folder: "Openstack"

- name: dashboards-varroa-overview
  files: [ dashboards/varroa.json ]
  options:
    annotations:
      grafana_folder: "Openstack"

#################################################
# Infrastructure Dashboards
#################################################

- name: dashboards-cert-manager-overview
  files: [ dashboards/cert-manager-overview.json ]
  options:
    annotations:
      grafana_folder: "Infrastructure"

#################################################
# Service Units Dashboards
#################################################

- name: dashboards-service-units-global
  files: [ dashboards/service_units_global.json ]
  options:
    annotations:
      grafana_folder: "Service Unit"

- name: dashboards-service-units-global2
  files: [ dashboards/service_units_global2.json ]
  options:
    annotations:
      grafana_folder: "Service Unit"

- name: dashboards-service-units-project
  files: [ dashboards/service_units_project.json ]
  options:
    annotations:
      grafana_folder: "Service Unit"

- name: dashboards-service-units-site
  files: [ dashboards/service_units_site.json ]
  options:
    annotations:
      grafana_folder: "Service Unit"
