{
 "title": "API Response",
 "tags": [ "coreservices" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "datasource", "query": "elasticsearch" },
   {
    "name": "api",
    "label": "API Host",
    "query": "keystone, nova, neutron, cinder, placement,"
   }
  ]
 },
 "panels": [
  {
   "title": "$api api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "api",
   "collapsed": true,
   "panels": [
    {
     "title": "Response time percentile [ $api ]",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:29",
         "field": "response_msecs",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:30",
         "field": "response_msecs",
         "id": "3",
         "meta": {},
         "settings": {
          "percents": [
           "50",
           "75",
           "90",
           "99"
          ]
         },
         "type": "percentiles"
        }
       ],
       "query": "api_host.keyword:\"$api.rc.nectar.org.au\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response code [ $api ]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "response",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "response",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "api_host.keyword:\"$api.rc.nectar.org.au\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response Msecs p75 [ $api ]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:280",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "response_msecs",
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": { "percents": [ "75" ] },
         "type": "percentiles"
        }
       ],
       "query": "api_host.keyword:\"$api.rc.nectar.org.au\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response Code [ $api ]",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "response",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "10", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "api_host.keyword:\"$api.rc.nectar.org.au\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Openstack api response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Response Msecs p75 [nova]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"nova.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"nova.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Msecs p75 [cinder]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {
        "percents": [
         "75",
         "90"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"cinder.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Msecs p75 [neutron]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {
        "percents": [
         "75",
         "90"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"neutron.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Msecs p75 [placement]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {
        "percents": [
         "75",
         "90"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"placement.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}