{
 "title": "Bumblebee Desktops",
 "tags": [ "virtual desktop" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "state", "label": "State", "query": "created,running,shelved" }
  ]
 },
 "panels": [
  {
   "title": "Total Desktops",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (bumblebee_desktops_created_total{})",
     "legendFormat": "Desktops ${state}"
    }
   ]
  },
  {
   "title": "Desktops running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (bumblebee_desktops_running_total{})"
    }
   ]
  },
  {
   "title": "Desktops shelved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (bumblebee_desktops_shelved_total{})"
    }
   ]
  },
  {
   "title": "Total desktops ${state}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (bumblebee_desktops_${state}_total{})",
     "legendFormat": "Desktops ${state}"
    }
   ]
  },
  {
   "title": "Desktops ${state} by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (type) (bumblebee_desktops_${state}_by_type{})",
     "legendFormat": "{{ type }} ${state}"
    }
   ]
  },
  {
   "title": "Desktops ${state} by zone",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (zone) (bumblebee_desktops_${state}_by_zone{})",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Desktops ${state} by domain",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (domain) (bumblebee_desktops_${state}_by_domain{})",
     "legendFormat": "{{ domain }} ${state}"
    }
   ]
  }
 ]
}