{
 "title": "Monitoring Instances - Cinder Storage Performance - all sites",
 "tags": [ "monitoring instances" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS - Sequential Read",
   "type": "timeseries",
   "description": "fio iops benchmark: blocksize=4k, iodepth=128",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "fio_read_iops_mean{benchmark=\"iops_read\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS - Sequential Write",
   "type": "timeseries",
   "description": "fio iops benchmark: blocksize=4k, iodepth=128",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "fio_write_iops_mean{benchmark=\"iops_write\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS - Random Read",
   "type": "timeseries",
   "description": "fio iops benchmark: blocksize=4k, iodepth=128",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "fio_read_iops_mean{benchmark=\"iops_randread\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS - Random Write",
   "type": "timeseries",
   "description": "fio iops benchmark: blocksize=4k, iodepth=128",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "fio_write_iops_mean{benchmark=\"iops_randwrite\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Throughput - Sequential Read",
   "type": "timeseries",
   "description": "fio throughput benchmark: blocksize=1m, iodepth=64",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "fio_read_bandwidth_kbps{benchmark=\"throughput_read\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput - Sequential Write",
   "type": "timeseries",
   "description": "fio throughput benchmark: blocksize=1m, iodepth=64",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "fio_write_bandwidth_kbps{benchmark=\"throughput_write\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput - Random Read",
   "type": "timeseries",
   "description": "fio throughput benchmark: blocksize=1m, iodepth=64",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "fio_read_bandwidth_kbps{benchmark=\"throughput_randread\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput - Random Write",
   "type": "timeseries",
   "description": "fio throughput benchmark: blocksize=1m, iodepth=64",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "fio_write_bandwidth_kbps{benchmark=\"throughput_randwrite\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Latency - Sequential Read",
   "type": "timeseries",
   "description": "fio latency benchmark: blocksize=4k, iodepth=1",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fio_read_lat_pct95{benchmark=\"latency_read\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency - Sequential Write",
   "type": "timeseries",
   "description": "fio latency benchmark: blocksize=4k, iodepth=1",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fio_write_lat_pct95{benchmark=\"latency_write\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency - Random Read",
   "type": "timeseries",
   "description": "fio latency benchmark: blocksize=4k, iodepth=1",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fio_read_lat_pct95{benchmark=\"latency_randread\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency - Random Write",
   "type": "timeseries",
   "description": "fio latency benchmark: blocksize=4k, iodepth=1",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fio_write_lat_pct95{benchmark=\"latency_randwrite\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}