{
 "title": "Monitoring Instances - Cinder Storage Performance - per site",
 "tags": [ "monitoring instances" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": "monitoring-adelaide.rc.nectar.org.au:19100,monitoring-ardc-syd-1.rc.nectar.org.au:19100,monitoring-auckland.rc.nectar.org.au:19100,monitoring-intersect.rc.nectar.org.au:19100,monitoring-melbourne-qh2-uom.rc.nectar.org.au:19100,monitoring-melbourne-qh2.rc.nectar.org.au:19100,monitoring-monash-01.rc.nectar.org.au:19100,monitoring-monash-02.rc.nectar.org.au:19100,monitoring-qriscloud.rc.nectar.org.au:19100,monitoring-swinburne-01.rc.nectar.org.au:19100,monitoring-tasmania-02.rc.nectar.org.au:19100,monitoring-tasmania-s.rc.nectar.org.au:19100,monitoring-tasmania.rc.nectar.org.au:19100,"
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "fio iops benchmark: blocksize=4k, iodepth=128",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "fio_read_iops_mean{benchmark=\"iops_read\", instance=\"$node\"}",
     "legendFormat": "read iops (sequential)"
    },
    {
     "expr": "fio_write_iops_mean{benchmark=\"iops_write\", instance=\"$node\"}",
     "legendFormat": "write iops (sequential)"
    },
    {
     "expr": "fio_read_iops_mean{benchmark=\"iops_randread\", instance=\"$node\"}",
     "legendFormat": "read iops (random)"
    },
    {
     "expr": "fio_write_iops_mean{benchmark=\"iops_randwrite\", instance=\"$node\"}",
     "legendFormat": "write iops (random)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "fio throughput benchmark: blocksize=1m, iodepth=64",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "fio_read_bandwidth_kbps{benchmark=\"throughput_read\", instance=\"$node\"}",
     "legendFormat": "read bandwidth (sequential)"
    },
    {
     "expr": "fio_write_bandwidth_kbps{benchmark=\"throughput_write\", instance=\"$node\"}",
     "legendFormat": "write bandwidth (sequential)"
    },
    {
     "expr": "fio_read_bandwidth_kbps{benchmark=\"throughput_randread\", instance=\"$node\"}",
     "legendFormat": "read bandwidth (random)"
    },
    {
     "expr": "fio_write_bandwidth_kbps{benchmark=\"throughput_randwrite\", instance=\"$node\"}",
     "legendFormat": "write bandwidth (random)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "fio latency benchmark: blocksize=4k, iodepth=1",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fio_read_lat_pct95{benchmark=\"latency_read\", instance=\"$node\"}",
     "legendFormat": "read latency (sequential)"
    },
    {
     "expr": "fio_write_lat_pct95{benchmark=\"latency_write\", instance=\"$node\"}",
     "legendFormat": "write latency (sequential)"
    },
    {
     "expr": "fio_read_lat_pct95{benchmark=\"latency_randread\", instance=\"$node\"}",
     "legendFormat": "read latency (random)"
    },
    {
     "expr": "fio_write_lat_pct95{benchmark=\"latency_randwrite\", instance=\"$node\"}",
     "legendFormat": "write latency (random)"
    }
   ]
  }
 ]
}