{
 "title": "Docker Container Metrics",
 "tags": [ "coreservices" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "query": {
     "query": "label_values(docker_container_cpu_percentage, host)"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(docker_container_cpu_percentage{host=~\"$host\"}, name)"
    }
   },
   { "name": "sumby", "label": "Sum By", "query": "name,host" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by ($sumby) (docker_container_memory_percentage{host=~\"$host\", name=~\"$container_name\"})",
     "legendFormat": "{{$sumby}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by ($sumby) (docker_container_cpu_percentage{host=~\"$host\", name=~\"$container_name\"})",
     "legendFormat": "{{$sumby}}"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($sumby) (rate(docker_container_block_io_read_bytes{host=~\"$host\", name=~\"$container_name\"}[5m]))",
     "legendFormat": "{{$sumby}} - Read"
    },
    {
     "expr": "sum by ($sumby) (rate(docker_container_block_io_write_bytes{host=~\"$host\", name=~\"$container_name\"}[5m]))",
     "legendFormat": "{{$sumby}} - Write"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($sumby) (docker_container_network_io_rx_bytes{host=~\"$host\", name=~\"$container_name\"})",
     "legendFormat": "{{$sumby}} - Received"
    },
    {
     "expr": "sum by ($sumby) (docker_container_network_io_tx_bytes{host=~\"$host\", name=~\"$container_name\"})",
     "legendFormat": "{{$sumby}} - Transmitted"
    }
   ]
  }
 ]
}