{
 "title": "Jupyter/Binder Users",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Jupyterhub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jupyter Total Users",
   "type": "stat",
   "description": "non-admin user accounts",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jupyterhub_total_users{job=\"jupyterhub\"}"
    }
   ]
  },
  {
   "title": "Current running jupyter notebooks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jupyterhub_running_servers{job=\"jupyterhub\"}"
    }
   ]
  },
  { "title": "Binderhub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Binder Total Users",
   "type": "stat",
   "description": "non-admin user accounts",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jupyterhub_total_users{job=\"jupyter\"}"
    }
   ]
  },
  {
   "title": "Current running binder notebooks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jupyterhub_running_servers{job=\"jupyter\"}"
    }
   ]
  }
 ]
}