{
 "title": "Jupyter/BinderHub Dashboard",
 "tags": [
  "jupyterhub",
  "binderhub"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Service", "query": "jupyterhub,binderhub" }
  ]
 },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "description": "non-admin user accounts",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_total_users{namespace=\"$namespace\"} or jupyterhub_total_users{instance=\"$namespace.rc.nectar.org.au:443\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notebook States (range)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"jupyter-.*\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hub usage stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current running users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  group(\n    kube_pod_status_phase{phase=\"Running\"}\n  ) by (pod, namespace)\n  * on (namespace, pod) group_right() \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (namespace)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "All users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jupyterhub_total_users{namespace=\"$namespace\"} or jupyterhub_total_users{instance=\"$namespace.rc.nectar.org.au:443\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "User CPU usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (pod) OR on() vector(0)\n"
    }
   ]
  },
  {
   "title": "User active age distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(\n  time()\n  - (\n    kube_pod_created\n    * on (namespace, pod)  \n  group(\n    kube_pod_labels{pod=~\"jupyter-.*\", namespace=\"$namespace\"}\n  ) by (pod, namespace)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "User memory usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\"}\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (pod) OR on() vector(0)\n"
    }
   ]
  },
  {
   "title": "Hub Diagnostics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All JupyterHub Components CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\nirate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{namespace=\"$namespace\"}\n  ) by (pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components Memory (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\ncontainer_memory_working_set_bytes{name!=\"\"}\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{namespace=\"$namespace\"}\n  ) by (pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "Server Start Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{job=\"$namespace\", status=\"success\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{job=\"$namespace\", status=\"success\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Hub response latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jupyterhub_request_duration_seconds_bucket{job=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(jupyterhub_request_duration_seconds_bucket{job=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Users per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # kube_pod_info.node identifies the pod node,\n    # while kube_pod_labels.node is the metrics exporter's node\n    kube_pod_info{node!=\"\"}\n    * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "timeseries",
   "description": "Pods in a non-running state in the hub's namespace.\n\nPods stuck in non-running states often indicate an error condition\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase!=\"Running\", namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Anomalous user pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Very old user pods",
   "type": "table",
   "description": "User pods that have been running for a long time (>8h).\n\nThis often indicates problems with the idle culler\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "(\n  time() - (kube_pod_created * on (namespace, pod)  \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace))\n) > (8 * 60 * 60)\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "User Pods with high CPU usage (>0.5)",
   "type": "table",
   "description": "User pods using a lot of CPU\n\nThis could indicate a runaway process consuming resources\nunnecessarily.\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current' value, so max will do\n  irate(container_cpu_usage_seconds_total[5m])\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (namespace, pod) > 0.5\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "User pods with high memory usage (>80% of limit)",
   "type": "table",
   "description": "User pods getting close to their memory limit\n\nOnce they hit their memory limit, user kernels will start dying.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current', but max will do. This metric is a gauge, so sum is inappropriate\n  container_memory_working_set_bytes\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (namespace, pod)\n/\nsum(\n  kube_pod_container_resource_limits_memory_bytes\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{namespace=\"$namespace\", pod=~\"jupyter-.*\"}\n  ) by (pod, namespace)\n) by (namespace, pod)\n> 0.8\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}