{
 "title": "Keystone Response",
 "tags": [ "coreservices" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Response time percentile",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:29",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:30",
       "field": "response_msecs",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"keystone.rc.nectar.org.au\" and request.keyword:\"/v3/auth/tokens\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 10, "y": 0 } },
  {
   "title": "Response code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "response",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "api_host.keyword:\"keystone.rc.nectar.org.au\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keystone Response Msecs p75",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "api_host.keyword:\"keystone.rc.nectar.org.au\" and request.keyword: \"/v3/auth/tokens\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keystone Response Msecs Runtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:35",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:33",
       "field": "response_msecs",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "api_host.keyword:\"keystone.rc.nectar.org.au\" and request.keyword: \"/v3/auth/tokens\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}