{
 "title": "Monitoring Tunnel Performance",
 "tags": [ "monitoring instances" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "query": "qriscloud, auckland, melbourne-qh2, intersect, melbourne-qh2-uom, monash-01, monash-02, swinburne-01, tasmania, tasmania-02,tasmania-s,adelaide,ardc-syd-1"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Performance FROM $site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(iperf3_received_bytes{job=~\"$site\"}[1h]) / avg_over_time(iperf3_received_seconds{job=~\"$site\"}[1h]) * 8)",
     "legendFormat": "$site as iperf client"
    }
   ]
  },
  {
   "title": "Average Performance TO $site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(iperf3_sent_bytes{job=~\"$site\"}[1h]) / avg_over_time(iperf3_sent_seconds{job=~\"$site\"}[1h]) * 8)",
     "legendFormat": "$site as iperf server"
    }
   ]
  },
  {
   "title": "Average Performance for All Monitoring Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg(iperf3_received_bytes / iperf3_received_seconds * 8)",
     "legendFormat": "iperf results for all instances"
    }
   ]
  },
  {
   "title": "Network Performance FROM $site Monitoring Instance ($site as iperf client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(iperf3_received_bytes{job=~\"$site\"}[1h]) / avg_over_time(iperf3_received_seconds{job=~\"$site\"}[1h]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Performance TO $site Monitoring Instance ($site as the iperf server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(iperf3_sent_bytes{job=~\"$site\"}[1h]) / avg_over_time(iperf3_sent_seconds{job=~\"$site\"}[1h]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}