{
 "title": "SDN Node Network Overview",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "node",
  "network",
  "coreservices"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds{job = 'coreservices_node_sdn'}, instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=~\"$node\"}, device)"
    }
   },
   { "name": "job", "query": "coreservices_node_sdn" }
  ]
 },
 "panels": [
  {
   "title": "Traffic In [24h] For All Overlay Interfaces Across 3 SDN Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[24h]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Traffic In [24h] For All Overlay Interfaces Across 3 SDN Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[24h]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Network Traffic Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Traffic In [24h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[24h]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Traffic out [24h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[24h]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Drop Package Rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_drop_total{device=~\"$device\",instance=~\"$node\"}[5m])/rate(node_network_transmit_packets_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{device=~\"$device\",instance=~\"$node\"}[5m])/rate(node_network_receive_packets_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Error Package Rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_errs_total{device=~\"$device\",instance=~\"$node\"}[5m])/rate(node_network_transmit_packets_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_errs_total{device=~\"$device\",instance=~\"$node\"}[5m])/rate(node_network_receive_packets_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Tcp_CurrEstab{instance=~\"$node\"}[1m]))",
     "legendFormat": "established"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"}[1m]))",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"}[1m]))",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_EstabResets{instance=~\"$node\"}[1m]))",
     "legendFormat": "estabResets"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_AttemptFails{instance=~\"$node\"}[1m]))",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[1m]))",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InErrors{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InCsumErrors{instance=~\"$node\"}[3m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[1m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"}) - sum(node_nf_conntrack_entries{instance=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}