{
 "title": "Varroa",
 "tags": [ "varroa" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Risks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(varroa_security_risks)", "legendFormat": "Total risks" }
   ]
  },
  {
   "title": "Affected Projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "varroa_projects_with_risks", "legendFormat": "Affected projects" }
   ]
  },
  {
   "title": "Total Risks History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sum(varroa_security_risks)", "legendFormat": "Total risks" }
   ]
  },
  {
   "title": "Risk Types Current",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (varroa_security_risks) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Risk Type History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(sum by (type) (varroa_security_risks))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}